# Generated by Django 5.0.9 on 2024-09-23 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.IntegerField(help_text='Discount percentage', validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(100)])),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
